apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 5  
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: devops-project-client
          image: welidwg/devops-project-client:12 
          ports:
            - containerPort: 3000  
