apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-new-deployment
spec:
  replicas: 5  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: welidwg/backend:16 
          ports:
            - containerPort: 3001 
