apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-final
spec:
  replicas: 5  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-final
          image: welidwg/backend-final:20
          ports:
            - containerPort: 3001 
