apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
        - name: cars-image
          image: welidwg/cars-image:22 
          ports:
            - containerPort: 5173  
            - containerPort: 5000  