apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-front
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: carsFront
  template:
    metadata:
      labels:
        app: carsFront
    spec:
      containers:
        - name: cars-image
          image: welidwg/cars-image:15 
          ports:
            - containerPort: 5173  
