apiVersion: v1
kind: Service
metadata:
  name: cars-frontend-service
  labels:
    app: carsFront
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 5173 
      
  selector:
    app: carsFront