apiVersion: v1
kind: Service
metadata:
  name: cars-loadbalancer-service
  labels:
    app: cars
spec:
  type: LoadBalancer
  ports:
    - name: frontend-http
      port: 80
      targetPort: 5173  # Port for the frontend (React)
    - name: backend-http
      port: 5000  # Port for the backend (Node.js)
  selector:
    app: cars