apiVersion: v1
kind: Service
metadata:
  name: cars-front-loadbalancer-service
  labels:
    app: carsFront
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  selector:
    app: carsFront